### ISSUE TITLE
Relatorios nao sao gerados

### ISSUE THREAD

**Issue by luc1anocruz** [rafaelmarques/mapos-hafael#2]
**Relatórios*
Não gera nenhum tipo de relatório.
Ao tentar gerar uma pagina em branco abre na mesma janela.

**Comment by rafaelmarques** [comment]
Os relatórios não atendiam minhas necessidades, comecei a modificar mas ia levar muito tempo pra deixar como eu queria. Ainda vou voltar a desenvolver essa parte, mas pra atender oq preciso foi mais rápido exportar os dados e gerar os relatórios fora. Pretendo criar uma área de relatórios bem flexível, mas não tenho prazo pra colocar no ar.
